name: Auto Project Assign

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: assing issue to project
        uses: AlexisMateo/issue-to-project-action@0.0.1
        with:
          # admin github token
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # the path to the project
          project_path: https://github.com/eretica/ci-playground/projects/1
