name: Auto Project Assign

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Echo
      run: echo "${{ toJson(github) }}"
    - name: Run assignment to project
      uses: srggrs/assign-one-project-github-action@1.1.0
      with:
        project: 'https://github.com/eretica/ci-playground/projects/1'
